version: "3.3"

services:
  etherpad:
    build:
      context: https://github.com/ether/etherpad-lite.git#release/1.8.5
      args:
        ETHERPAD_PLUGINS: "ep_align ep_author_hover ep_comments_page ep_copy_paste_images ep_headings2 ep_who_did_what"
    ports:
      - 80:9001
    environment:
      ADMIN_PASSWORD: "admin"
